src/themes/radius.ts
- closed #12 
- button 컴포넌트에 필요한 radius 속성 추가
- button 컴포넌트에 들어가는 round 값을 위해 radius100 속성값을 추가했습니다.
- 기존에 있던 속성값들은 radius 이후에 들어가는 숫자값에서 0을 제거했습니다. (`radius04` -> `radius4`)
=> chore: theme radius 속성 추가

.storybook/main.js, src/styles/font.ts
- closed #18 
- 배포된 storybook에 font face를 적용하였습니다.
[링크는 요깃!](https://630c98d15c06a386dbef7c66-qmkqqbvogn.chromatic.com/?path=/story/component-test--test-component)
- font를 root 경로로 변경하였습니다.
- 빌드 시, static 폴더를 포함할 수 있도록 staticDir을 설정 해주었습니다.
=> config: chromatic font face 적용

src/styles/themes/fonts.ts
- closed #28 
- font 스타일을 text 컴포넌트에서 적용하기 용이하도록 구조를 변경합니다.
- 개선된 점
- text 스타일을 적용하는 방식이 간단해짐
- theme에서 font style을 불러오는 경우 참조가 한번 줄어듦
=> feat: theme font 구조 변경

src/styles/global.tsx
- closed #39 
- global font color는 theme에 있는 grayScale[gray90]으로 지정
=> chore: global font color 추가

src/styles/themes/colors.ts
- closed #44 
- modal `box-shadow`에 사용되는 opacity40 컬러 추가
=> chore: theme color dim 추가

src/components/Button/index.tsx, src/components/Text/Text.stories.tsx
=> design: Button 컴포넌트 디자인 및 Storybook control 수정

.husky/pre-commit, package.json, src/components/Button/index.tsx, src/components/Carousel/index.tsx
- closed #59 
- ts로 컴파일과 함께 lint 체크를 하여 eslint 동작 시, ts 오류는 잡지 못하는 현상을 해결하였습니다.
- pre-commit 파일 수정, prepare을 등록하여 husky가 동작하지 않는 오류를 해결하였습니다.
- icon type에 대한 props가 iconType으로 되어있어 오류가 발생하던 부분을 해결하였습니다.
=> fix: husky 동작 이슈 디버깅, icon 컴포넌트 수정 사항 적용

src/components/Image/index.tsx, src/components/Radio/Radio.stories.tsx
- closed #62 
- 세미콜론으로 인해 Image Component의 background가 적용 안되는 오류를 디버깅하였습니다.
- Radio Component 스토리북의 onChange 타입 오류를 디버깅하였습니다.
=> fix: Image Component Background-color 오류 디버깅 및 radio onChange 오류 디버깅

src/components/Badge/Badge.stories.tsx, src/components/Badge/index.tsx, src/components/Button/Button.stories.tsx, src/components/Button/index.tsx, src/components/ChattingBubble/ChattingBubble.stories.tsx, src/components/ChattingBubble/index.tsx, src/components/Divider/Divider.stories.tsx, src/components/Divider/index.tsx, src/components/IconButton/IconButton.stories.tsx, src/components/IconButton/index.tsx, src/components/ImageModal/index.tsx, src/components/ImageUploader/ImageUploader.stories.tsx, src/components/ImageUploader/index.tsx, src/components/ImageUploader/uploader/DesktopUploader.tsx, src/components/ImageUploader/uploader/MobileUploader.tsx, src/components/ImageUploader/useImageUploader.ts, src/components/Input/ChattingInput.tsx, src/components/Input/Input.stories.tsx, src/components/Input/index.tsx, src/components/Modal/index.tsx, src/components/SelectBox/SelectBox.stories.tsx, src/components/SelectBox/index.tsx, src/components/Text/Text.stories.tsx, src/components/Text/index.tsx, src/components/ToggleButton/ToggleButton.stories.tsx, src/components/ToggleButton/index.tsx, src/types/offer.d.ts
- closed #77 
- merge로 인해 base가 덮어 씌워져 rebase를 하였습니다.
=> config: merge 문제로 git rebase

src/components/ImageModal/index.tsx
- closed #70 
- ImageModal 내부 스타일 수정
- 인디케이터, 클로즈 버튼 위치 화면 크기에 따라서 달라지도록 수정
=> design: ImageModal  디자인 수정

README.md, package.json, packages/react/package.json
- closed #87 
- 리드미 현재 package로 경로 설정하였습니다.
- package 버전 업 시켰습니다.
=> docs: readme 설정 및 패키지 버전 업

packages/react/package.json
- closed #91 
- 불필요한 kill-port 명령어를 제거 하였습니다.
=> chore: 불필요한 명령어 제거 

packages/react/src/components/Avatar/index.tsx, packages/react/src/components/Badge/index.tsx, packages/react/src/components/Button/index.tsx, packages/react/src/components/Carousel/index.tsx, packages/react/src/components/ChattingBubble/index.tsx, packages/react/src/components/Divider/index.tsx, packages/react/src/components/Icon/index.tsx, packages/react/src/components/IconButton/index.tsx, packages/react/src/components/Image/index.tsx, packages/react/src/components/ImageModal/index.tsx, packages/react/src/components/ImageUploader/index.tsx, packages/react/src/components/Input/index.tsx, packages/react/src/components/Modal/index.tsx, packages/react/src/components/Radio/index.tsx, packages/react/src/components/SelectBox/index.tsx, packages/react/src/components/Text/index.tsx, packages/react/src/components/Textarea/index.tsx, packages/react/src/components/ToggleButton/ToggleButton.stories.tsx, packages/react/src/components/ToggleButton/index.tsx, packages/react/src/hooks/useClickAway.ts, packages/react/src/hooks/useClose.ts, packages/react/src/hooks/useImage.ts, packages/react/src/hooks/useMediaQuery.ts
- closed #96 
- 컴포넌트의 props에 대한 jsDoc을 작성 하였습니다.
- 훅의 props에 대한 jsDoc을 작성 하였습니다.
=> docs: component, hook에 대한 jsdocs 작성

packages/react/src/components/Avatar/index.tsx, packages/react/src/components/Badge/index.tsx, packages/react/src/components/Button/index.tsx, packages/react/src/components/Carousel/index.tsx, packages/react/src/components/ChattingBubble/index.tsx, packages/react/src/components/Divider/index.tsx, packages/react/src/components/Icon/index.tsx, packages/react/src/components/IconButton/index.tsx, packages/react/src/components/Image/index.tsx, packages/react/src/components/ImageModal/index.tsx, packages/react/src/components/ImageUploader/index.tsx, packages/react/src/components/ImageUploader/uploader/DesktopUploader.tsx, packages/react/src/components/ImageUploader/uploader/MobileUploader.tsx, packages/react/src/components/Input/ChattingInput.tsx, packages/react/src/components/Input/DefaultInput.tsx, packages/react/src/components/Input/EditInput.tsx, packages/react/src/components/Input/SearchInput.tsx, packages/react/src/components/Input/index.tsx, packages/react/src/components/Modal/index.tsx, packages/react/src/components/Radio/index.tsx, packages/react/src/components/SelectBox/index.tsx, packages/react/src/components/Text/index.tsx, packages/react/src/components/Textarea/index.tsx, packages/react/src/components/ToggleButton/ToggleButton.stories.tsx, packages/react/src/components/ToggleButton/index.tsx, packages/react/src/hooks/useClickAway.ts, packages/react/src/hooks/useClose.ts, packages/react/src/hooks/useImage.ts, packages/react/src/hooks/useMediaQuery.ts
- closed #99 
- Text 컴포넌트를 기존 컴포넌트에 반영 했습니다.
- 컴포넌트 순환 참조 이슈를 해결 했습니다.
=> feat: Text Component 반영

package.json, packages/react/package.json, yarn.lock
- jsdocs 작성
- Text Component 반영
- forwardRef 적용
- 타입 개선
=> release: v0.0.10 upgrade

packages/react/src/components/Modal/index.tsx, yarn.lock
- closed #108
* 모달 스크롤 시 백그라운드 스크롤 되지 않도록 수정
* 모달 컨텐츠가 길어지는 경우 스크롤 가능하도록 수정
* 아이콘 버튼은 패키지 모달에서 제거되는 것이 좋을 것 같아 제거했습니다! 닫기 여부는 사용자에게 맏기는 것이 좋을 것 같아용
=> fix: 모달 컴포넌트 스크롤 이슈 수정

package.json, packages/react/package.json
=> release: v0.1.4 upgrade

packages/react/src/components/ImageModal/index.tsx, packages/react/src/components/Modal/Modal.stories.tsx, packages/react/src/components/Modal/index.tsx
- 모달 ssr 환경 대응
- 이미지 모달 ssr 환경 대응
- document를 찾지 못하는 이슈 해결을 위해 useMemo 사용을 useState사용으로 변경했습니다.
=> release: v0.1.6 upgrade

package.json, packages/react/package.json
=> release: update v0.1.6

package.json, packages/react/package.json
=> release: update v0.1.10

package.json, packages/react/package.json
* 이전 버전에 빌드를 빼묵어서 버전 하나 더 올립니다 🥲
=> release: v0.1.11

package.json, packages/react/package.json
=> release: update v0.1.12

package.json, packages/react/package.json
=> release: update v0.1.13

package.json, packages/react/package.json
=> release: update v0.1.14

package.json, packages/react/package.json
=> release: update v0.1.5

packages/react/src/components/Input/EditInput.tsx, packages/react/src/components/Text/Text.stories.tsx, packages/react/src/components/Text/index.tsx, packages/react/src/components/Textarea/index.tsx
- closed #140 
* Text components color prop 타입 좁히기 및 변경 사항 적용
=> feat: color를 prop으로 받는 컴포넌트들 type 좁히기

packages/react/src/components/Button/Button.stories.tsx, packages/react/src/components/Button/index.tsx, packages/react/src/components/IconButton/index.tsx, packages/react/src/components/Text/index.tsx, packages/react/src/components/ToggleButton/ToggleButton.stories.tsx, packages/react/src/components/ToggleButton/index.tsx
- closed #142 
* toggle Button의 prop을 수정
* toggle Button이 toggle시 색상만 지정할 수 있어 toggle시 아이콘도 변경할 수 있도록 변경
* Button prop에 width 추가
* 버튼 컴포넌트에 width값을 주어야 하는 경우를 위해 prop을 추가 
https://user-images.githubusercontent.com/70738281/213838458-d54214dd-01a6-43d8-afa5-494fd659fc2c.mov
=> feat: 컴포넌트 사용성을 위한 prop 수정

packages/react/src/components/SelectBox/SelectBox.stories.tsx, packages/react/src/components/SelectBox/index.tsx, packages/react/src/types/offer.d.ts
- closed #135 
- SelectBox 컴포넌트를 uncontrolled 컴포넌트, controlled 컴포넌트로 사용할 수 있도록 개선 하였습니다.
- SelectBox의 z-index를 적용 시켰습니다.
- SelectBox 컴포넌트를 uncontrolled 컴포넌트, controlled 컴포넌트로 사용할 수 있도록 개선 하였습니다.
- value가 있는 경우, controlled 컴포넌트로 동작할 수 있도록 onChange를 필수 타입으로 지정하였습니다.
- value, onChange가 없는 경우, 이전의 구현 형태 처럼 uncontrolled 컴포넌트로 동작합니다.
=> refactor: Select Component 구조 변경 및 버그 개선

package.json, packages/react/package.json
=> release: update v0.1.16

packages/react/src/components/SelectBox/SelectBox.stories.tsx, packages/react/src/components/SelectBox/index.tsx, packages/react/src/types/offer.d.ts
- closed #150 
기존의 { value, text }에서 api 구조와 동일하게 { code, name }으로 변경 하였습니다.
=> refactor: SelectBox api 구조에 맞게 변경

packages/react/src/components/SelectBox/SelectBox.stories.tsx, packages/react/src/components/SelectBox/index.tsx, packages/react/src/types/offer.d.ts
- SelectBox 컴포넌트의 code 타입 제네릭으로 확장 하였습니다.
- 이전 수정 사항의 불필요한 타입을 제거 하였습니다.
=> fix: selectBox 타입 확장 및 불필요한 타입 제거

package.json, packages/react/package.json
=> release: release v0.1.18

packages/react/src/components/Carousel/index.tsx, packages/react/src/hooks/useMedia.tsx
- closed
캐러젤 인디케이터 height값이 없어 다른 요소와 결합시 겹처 보이는 현상 및
첫 화면 렌더시 이미지 size를 제대로 못가져오는 이슈를 대응합니다. (useMediaquery원인)
=> fix:캐러젤 이슈대응

package.json, packages/react/package.json
=> release: update v0.1.19

package.json, packages/react/package.json
- v0.1.4
- 캐러젤 이슈대응
- input 디자인 대응
- 타입추가
=> release:v 0.1.21

packages/react/src/hooks/useMedia.tsx
- closed #157 
- layoutEffect로 전달
=> fix:캐러셀  layout effect 적용

package.json, packages/react/package.json
=> release:v0.1.22

package.json, packages/react/package.json
=> release: update v0.1.23

package.json, packages/react/package.json
=> release: v0.1.24

packages/react/src/components/Radio/index.tsx
closed #171 
radio 이슈가 있어 제거합니다.
Radio render prop의 name params를 any타입으로 변경 필요
Radio margin-bottom 제거 필요
Radio label 쪽 background 색 제거 필요
=> fix: radio 이슈 해결

packages/react/src/types/index.ts
- closed #176 
* declare 타입 패키지에 내보내지 않도록 export 제거
=> config: emotion declare type 제거

package.json, packages/react/package.json
*  package version upgrade v0.1.25
=> release: release: v0.1.25

packages/react/src/components/Button/Button.stories.tsx, packages/react/src/components/Button/index.tsx, packages/react/src/components/Button/styled.ts, packages/react/src/components/Button/types.ts, packages/react/src/components/Input/Input.stories.tsx
- closed #186 
* Button 컴포넌트 disabled 타입 수정
* 기존에 styleType에 disabled 타입이 따로 있었는데 요 디자인을 disabled prop에따라 적용되도록 수정합니다.
=> feat: Button 컴포넌트 disabled 타입 수정

packages/react/src/components/ImageModal/index.tsx
- closed #188 
* 불필요한 상태 제거
*  매직 리터럴 제거
*  코드 정리
* reduce가 의도된 사용과 다르게 사용되고 있어서 for문으로 변경했습니다.
* topElement 값이 불필요하게 state로 관리되고 있어서 ref로 변경했습니다.
=> refactor: ImageModal 코드 정리

packages/react/src/components/Input/index.tsx
불필요한 타입 undefined가 포함되어 있는 것 같아서 삭제하였습니다
만약 의도하신거라면 정말 죄송합니다 ㅠㅠ..
=> chore: 불필요한 타입 삭제

packages/react/src/components/Text/index.tsx
- 불필요한 타입 제거
- 디폴트 매개변수 black 추가
=> fix: text component

package.json, packages/react/package.json
- closed 
upgrade v0.1.26
* #193 
* #191 
* #190 
* #189 
* #187 
* #185 
* #183
=> release: v0.1.26

packages/react/src/components/SelectBox/index.tsx
- closed #196 
* Selectbox width값 변경에 용이하도록 수정
=> design: Selectbox width값 변경에 용이하도록 수정

package.json, packages/react/package.json
- closed
upgrade v0.1.26
* #197 
* #198
=> release: v0.1.27

packages/react/src/components/Avatar/Avatar.stories.tsx, packages/react/src/components/Badge/Badge.stories.tsx, packages/react/src/components/Button/Button.stories.tsx, packages/react/src/components/Carousel/Carousel.stories.tsx, packages/react/src/components/ChattingBubble/ChattingBubble.stories.tsx, packages/react/src/components/CheckBox/CheckBox.stories.tsx, packages/react/src/components/Divider/Divider.stories.tsx, packages/react/src/components/Icon/Icon.stories.tsx, packages/react/src/components/IconButton/IconButton.stories.tsx, packages/react/src/components/Image/Image.stories.tsx, packages/react/src/components/ImageModal/ImageModal.stories.tsx, packages/react/src/components/ImageUploader/ImageUploader.stories.tsx, packages/react/src/components/Input/Input.stories.tsx, packages/react/src/components/Modal/Modal.stories.tsx, packages/react/src/components/Radio/Radio.stories.tsx, packages/react/src/components/SelectBox/SelectBox.stories.tsx, packages/react/src/components/Text/Text.stories.tsx, packages/react/src/components/Textarea/Textarea.stories.tsx, packages/react/src/components/ToggleButton/ToggleButton.stories.tsx
- closed #202 
- 기존의 스토리 파일들을 스토리북 v7의 컨벤션으로 변경하였습니다.
=> refactor: story 파일 v7로 변경

apps/ods-playground/package.json
- 불필요한 build를 하고 있는 명령어를 제거하였습니다.
=> fix: remove unnecessary build script

packages/react/CHANGELOG.md, packages/react/package.json
ods version upgrade
- chromatic storybook migration v7
- react storybook migration v7
- node migration lts
- add changeset
=> docs: release note

.changeset/config.json, .changeset/sweet-avocados-knock.md, .changeset/tall-avocados-share.md, .changeset/tough-scissors-drive.md
- CD 환경에서 changeset 에러가 발생하여 수정하였습니다.
=> config: changeset ignore 수정

packages/react/src/components/Image/index.tsx
- closed #221 
- #218가 논이슈 처리되어 이전 버전으로 되돌렸습니다.
- 사용하는 쪽에서 style시트로 사용하지 않으면 우선 순위로 반영되는 이슈가 있어스타일 시트에서 string으로 수정하였습니다.
=> fix: 이미지 깨짐 현상 수정

.changeset/wicked-mirrors-trade.md
=> release: v0.2.2

apps/ods-playground-next/next.config.js, apps/ods-playground-next/package.json, apps/ods-playground-react/package.json
- playground에 스타일링을 위한 emotion 패키지를 설치하였습니다.
=> config: playground에 스타일링을 위한 emotion 패키지 설치

packages/react/src/components/Icon/index.tsx, packages/react/src/components/ImageUploader/index.tsx, packages/react/src/components/ImageUploader/useImageUploader.ts, packages/react/src/hooks/useMediaQuery.ts, yarn.lock
- closed #230 
* 이미지 업로드시 onChange param에 상태 업데이트 늦게되는 이슈 수정
* 이미지 업로더 next 환경에서 hydration 이슈 수정
**hydration 이슈**
* 원인: mobile, tablet 화면에서 이미지 업로더를 그릴 때 화면 분기를 위해 사용되는 `useMediaQuery` 가 주는 값이 서버측 렌더링(false - pc)일 때와 화면에서 보여주는 값(true -mobile, tablet)이 달라 이슈 발생
* 해결 방안: 초기값을 true로 통일하고 `useIsomorphicLayoutEffect` 를 사용해 useMediaQuery의 mobile, tablet 화면에서 초기값에 의해 pc 화면이 렌더링 되지 않도록 방지
=> fix: ImageUploader 컴포넌트 상태 업데이트 및 전달 데이터 수정

packages/react/src/components/Radio/Default.tsx, packages/react/src/components/Radio/Input.tsx
- closed #231 
* Radio 선택 값 외부에서 지정할 수 있도록 수정
=> feat: Radio 값 reset 할 수 있도록 수정

packages/react/src/components/Badge/index.tsx
- closed #244 
* 뱃지 컴포넌트 높이값 틀어지지 않도록 수정
_**문제되는 이슈**_
=> design: 뱃지 컴포넌트 높이값 틀어지지 않도록 수정

packages/react/src/components/ImageUploader/useImageUploader.ts
- closed #243 
* ImageUploader 컴포넌트 상위에서 내려준 data와 싱크 맞추기
* 상위에서 패치된 데이터를 사용해서 상태를 내려줄 때 값이 변경돼도 컴포넌트 내에서는 기본 값으로만 사용되고 있기 때문에 패치된 데이터 반영이 이뤄지지 않아 싱크업을 위한 작업을 했습니다.
=>  feat: ImageUploader 컴포넌트 상위에서 내려준 data와 싱크 맞추기

.changeset/empty-jeans-greet.md, packages/react/src/components/Carousel/Carousel.stories.tsx, packages/react/src/components/Carousel/index.tsx, packages/react/src/components/ImageModal/ImageModal.stories.tsx, packages/react/src/components/ImageModal/index.tsx
- closed #252 
* Carousel, ImageModal 컴포넌트 prop 통일
* Carousel, ImageModal 컴포넌트 images 없는 경우 대응
* Carousel Image 컴포넌트 사용하도록 수정
=> feat: Carousel, ImageModal 컴포넌트 개선 

packages/react/src/components/Carousel/index.tsx, packages/react/src/components/ImageModal/index.tsx
- closed #252 
* Carousel 이미지 있는 경우엔 배경색 갖지 않도록
* ImageModal DIM 고정하기
=> design: Carousel, ImageModal 디자인 수정

packages/react/src/components/Input/Chatting.tsx, packages/react/src/components/Input/Default.tsx, packages/react/src/components/Input/Edit.tsx, packages/react/src/components/Input/Input.stories.tsx, packages/react/src/components/Input/Search.tsx, packages/react/src/components/Input/index.tsx
- closed #255 
* Input 컴포넌트 코드 개선
* submit시 실행할 prop 추가
=> refactor:  refactor: Input 컴포넌트 개선

.changeset/serious-zoos-retire.md, packages/react/src/components/Input/Edit.tsx
*  Edit-Input isPrice에 따른 디자인 변화
* 코드가 날라가서 다시 추가함니다
=> design: Edit-Input isPrice에 따른 디자인 변화

packages/react/src/components/Input/Edit.tsx
- closed #270 
* Input.Edit 컴포넌트 한국어 maxLength 이상으로 입력되는 이슈 수정
=> fix: Input.Edit 컴포넌트 한국어 maxLength 이상으로 입력되는 이슈 수정 
