price-offer/offer-design-system

src/styles/global.tsx
- closed #21 
- font weight에 기본값을 설정해두지 않으니 임의로 400으로 설정되어 regular로 정해두었습니다!
미세하게 얇아졌습니다 ㅎㅎ
=> chore: global font face regular로 설정

src/styles/font.ts, src/styles/global.tsx, src/styles/themes/fonts.ts
- closed #23 
- font-family에 잘못 정의해둔 폰트명을 수정하였습니다.
- font-weight 400이 기본 값으로 적용되어 medium이 기본값으로 설정이 되어 500으로 따로 정의해주었습니다
- theme/font.ts의 medium 대신 500을 사용할 수 있도록 반영 해 두었습니다.
폰트 설정으로 번거롭게 해서 죄송해융 ㅠㅅㅠ!!
**font-weight**
- normal: regular
- 500: medium
- bold: bold
좌측 값으로 설정하게 되면 font weight가 적용됩니다!
=> chore: font face 설정 오류 개선, 기본값 regular로 재지정 

.eslintrc.json, package.json, src/components/Test/index.tsx, yarn.lock
**typescript 버전이 변경되어 브랜치 merge하시면 `yarn` 입력하셔서 패키지 꼭 새로 받아쥬세용!!!**
- closed #26 
- [self-closing-comp: error - 빈 태그인 경우, single 태그로 변경](https://github.com/jsx-eslint/eslint-plugin-react/blob/master/docs/rules/self-closing-comp.md)
- [no-explicit-any: error - any 사용시, 에러 발생](https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/docs/rules/no-explicit-any.md)
**해결 방안**
- package.json scripts lint의 `./src/**/*.{ts, tsx}` 부분을 single quote로 감싸주어 해결
**상세 내용**
- typescript 버전이 lint tree에서 지원되지 않는 버전
- react 버전이 lint에 명시되어 있지 않음
**해결 방안**
- typescript 버전이 지원되지 않는 버전이라 하여 지정된 범위 내의 버전을 명시하는 것으로 해결하였습니다.
- .eslintrc.json 파일에 react 버전 명시하는 것으로 해결 하였습니다.
=> config: eslint rule 추가 및 lint 디버깅

.eslintrc.json
- closed #42 
- useEffect를 사용하면서 발생한 lint 에러를 해결하기 위해 `consistent-return` 룰을 제거
- useEffect를 사용할 때 `consistent-return`에러 발생
- 이슈 원인
- early return 타입과, cleanUp return의 타입이 달라서 발생하는 에러
- 시도한 방법
- early return 시 cleanUp return 타입인 `() => void`와 맞추기 위해 `return () => null`을 사용
- 해결 방안
- lint 룰에서 `consistent-return`을 제거
=> config: eslint 설정 변경

src/components/Badge/Badge.stories.tsx, src/components/Badge/index.tsx, src/components/Button/Button.stories.tsx, src/components/Carousel/Carousel.stories.tsx, src/components/Divider/Divider.stories.tsx, src/components/Text/Text.stories.tsx, src/styles/themes/fonts.ts
- closed #42 
- caption01M 폰트 타입 추가
- 폰트 굵기가 네이밍에 들어가지 않은 타입에 굵기 추가 (ex) `display01` => `display01B`)
- storybook 디렉토리를 회의에서 정한 컨벤션인 Default로 통일[(참고 문서)](https://fate-squirrel-cd0.notion.site/66565a38db2241b2868c8aa4a4322af2)
=> chore: font 수정 및 storybook 컨벤션 통일화

src/components/Carousel/index.tsx
- closed #50 
캐러젤  터치슬라이드 이벤트가 반대 전환시 한번 무시되는 현상 수정
이미지 전환 발생마다 x좌표 상태(StartClientX,EndClientX) 초기화 및 의존성에 추가하여 최신화
=> fix: 캐러젤 터치슬라이드 이벤트가 간헐적으로 안되는 현상 수정

.storybook/manager-head.html, .storybook/manager.js, .storybook/theme.js
- closed #41 
스토리북 로고, 파비콘 변경
스토리북의 로고 및 파비콘변경 작업을 위해 ./storybook 폴더에 theme, manager-head를 추가하였습니다.
=> chore: storybook logo,favicon 변경

src/components/Badge/Badge.stories.tsx, src/components/Badge/index.tsx, src/components/Button/Button.stories.tsx, src/components/Button/index.tsx, src/components/ChattingBubble/ChattingBubble.stories.tsx, src/components/ChattingBubble/index.tsx, src/components/Divider/Divider.stories.tsx, src/components/Divider/index.tsx, src/components/IconButton/IconButton.stories.tsx, src/components/IconButton/index.tsx, src/components/ImageModal/index.tsx, src/components/ImageUploader/ImageUploader.stories.tsx, src/components/ImageUploader/index.tsx, src/components/ImageUploader/uploader/DesktopUploader.tsx, src/components/ImageUploader/uploader/MobileUploader.tsx, src/components/ImageUploader/useImageUploader.ts, src/components/Input/ChattingInput.tsx, src/components/Input/Input.stories.tsx, src/components/Input/index.tsx, src/components/Modal/index.tsx, src/components/SelectBox/SelectBox.stories.tsx, src/components/SelectBox/index.tsx, src/components/Text/Text.stories.tsx, src/components/Text/index.tsx, src/components/ToggleButton/ToggleButton.stories.tsx, src/components/ToggleButton/index.tsx, src/types/offer.d.ts
- closed #69 
- props명 통일과 Button 컴포넌트 오타를 수정하였습니다.
- styleType → 색상 및 형태 변경
- color → 색상 변경 (hexcolor)
- colorType 색상 변경 (내부 지정된 string)
- ~~colorScheme~~ → colorType
- ~~orientation~~ → direction
- ~~imageList~~ → images
- ~~colorScheme~~ → colorType
- ~~options~~ → items
- ~~type~~ → messageType
- ~~formName~~ → name
- ~~textStyle~~ → styleType
- ~~buttonStyle~~ → styleType
- ~~iconType~~ → icon
- ~~color~~ → colorType
- ~~color~~ → colorType
- ~~toggleColor~~ → toggleColorType
- ~~inputStyle~~ → styleType
=> refactor: props명 통일, Button 컴포넌트 오타 수정

packages/react/.eslintrc.json, packages/react/src/components/Avatar/index.tsx, packages/react/src/components/Badge/index.tsx, packages/react/src/components/Button/index.tsx, packages/react/src/components/Carousel/index.tsx, packages/react/src/components/ChattingBubble/index.tsx, packages/react/src/components/Divider/index.tsx, packages/react/src/components/Icon/index.tsx, packages/react/src/components/IconButton/index.tsx, packages/react/src/components/Image/index.tsx, packages/react/src/components/ImageModal/index.tsx, packages/react/src/components/ImageUploader/index.tsx, packages/react/src/components/ImageUploader/uploader/DesktopUploader.tsx, packages/react/src/components/ImageUploader/uploader/MobileUploader.tsx, packages/react/src/components/Input/ChattingInput.tsx, packages/react/src/components/Input/DefaultInput.tsx, packages/react/src/components/Input/EditInput.tsx, packages/react/src/components/Input/SearchInput.tsx, packages/react/src/components/Input/index.tsx, packages/react/src/components/Modal/index.tsx, packages/react/src/components/Radio/index.tsx, packages/react/src/components/Text/index.tsx, packages/react/src/components/Textarea/index.tsx, packages/react/src/components/ToggleButton/index.tsx, packages/react/src/hooks/useClickAway.ts, packages/react/src/utils/mergeRefs.ts
- closed #101 
- 컴포넌트에 forwardRef를 적용하였습니다.
- HTMLAttribute<T> 타입 선언 시, 특정 엘리먼트의 속성을 불러오지 못하는 이슈가 있어 타입을 수정하였습니다.
- 기존의 ref가 적용되어 있는 경우, 추가 ref를 등록하기 위해 mergeRefs 유틸 함수를 구현 하였습니다.
- Modal, ImageModal에 forwardRef를 적용하면 useEffect의 클린업 함수에 리턴 타입을 명시를 하라는 린트 에러가 발생 합니다.. 혹시 원인 아시는 분 계신가용!?
- 우선 void로 명시해두었습니당!
=> refactor: forwardRef 적용 및 HTMLAttribute 타입 리팩터링

packages/react/src/components/Modal/Modal.stories.tsx, packages/react/src/components/Modal/index.tsx
- closed #114 
*  Modal width, height 지정을 더 자유롭게 하기 위해 props type을 number -> string으로 변경
=> feat: Modal props 타입 수정

packages/react/src/components/Button/Button.stories.tsx, packages/react/src/components/Button/index.tsx
=> design: 버튼 컴포넌트 너비 고정 해제 

packages/react/src/components/Badge/index.tsx, packages/react/src/components/Text/index.tsx
- closed #125
- Badge, Text 타입에 자바스크립트 표현식이 들어가지 않는 오류를 개선 하였습니다.
```tsx
// Error ❌
<Badge>Lv.{level}</Badge>
```
위와 같이 표현식을 같이 적는 경우, 오류가 발생하여 ReactNode로 children을 변경 하였습니다.
=> fix: Badge 컴포넌트 children 타입 오류 수정 

packages/react/src/components/Button/index.tsx
- closed #129 
* Badge 컴포넌트 children 타입을 ReactNode로 수정
=> fix: Button 컴포넌트 children 타입 오류 수정 

packages/react/src/components/Divider/Divider.stories.tsx, packages/react/src/components/Divider/index.tsx, packages/react/src/components/Icon/Icon.stories.tsx, packages/react/src/components/IconButton/IconButton.stories.tsx, packages/react/src/components/IconButton/index.tsx, packages/react/src/components/ImageModal/index.tsx, packages/react/src/components/Input/ChattingInput.tsx, packages/react/src/components/ToggleButton/ToggleButton.stories.tsx, packages/react/src/components/ToggleButton/index.tsx
- closed #132 
* IconButton 사이즈 조절이 되지 않는 이슈 수정 및 변경사항 적용
* Divider 간격, 사이즈 조절 prop 추가
* Icon Button은 구두로 회의를 통해 ghost 타입만 남겨두는 것으로 결정하여 수정완료 했습니다.
* Divider 사이즈 조절을 위한 prop들이 받아지지 않고있어 추가했습니다.
=> fix: IconButton, Divider 이슈 수정

packages/react/src/components/Badge/index.tsx
- closed #147 
* Badge 컴포넌트 텍스트 색상 적용 안되는 이슈 수정
* Text 컴포넌트 내부에서 이미 컬러 값을 지정하고 있기 때문에 상위에서 전해주는 컬러값이 우선순위에서 밀려나서 적용되지 않는 이슈
* Text 컴포넌트에 직접 color를 prop으로 내려주는 방식으로 수정
=> fix: Badge 컴포넌트 텍스트 색상 적용 안되는 이슈 수정

packages/react/src/components/Text/index.tsx
- closed #152 
* Text 사용시 기본 색상 지정이 되어있어 상위에서 색상 지정이 불가능하기 때문에 이를 제거합니다.
=> design: Text 기본 색상값 제거

packages/react/src/components/Badge/index.tsx, packages/react/src/components/Button/index.tsx, packages/react/src/components/SelectBox/SelectBox.stories.tsx, packages/react/src/components/Text/index.tsx, packages/react/src/types/offer.d.ts
- SelectBox 내부 엄격한 타입 선언으로 인해 외부 사용처에서 타입 지정이 어려워 any로 변경하였습니다...
- ReactNode관련 Exclude 되어있는 string을 해당 타입으로 재지정하였습니다.
=> refactor: Selectbox 타입 이슈로 인해 any로 item 타입 확장, ReactNode관련 타입 재지정

packages/react/.eslintrc.json, packages/react/src/components/CheckBox/hooks/index.ts, packages/react/src/components/CheckBox/index.tsx, packages/react/src/components/Radio/index.tsx, packages/react/src/components/SelectBox/index.tsx, packages/react/src/types/offer.d.ts
- closed #168 
-  { code, name }으로 받는 형태에 대한 타입 확장
- any 제한하는 린트 룰 제거
=> refactor: { code, name }으로 받는 형태에 대한 타입 확장

packages/react/public/icons/smile.svg
- closed #192 
- Icon 컴포넌트 smile 이 width, height, stroke-width 가 유지가 안되고 깨지는 현상 확인 후 수정
이와 같이 동일하게 stroke-width 가 2인데 smile 만 두껍다. 
따라서 vector-effect 의 "non-scaling-stroke" 이라는 비율에 따라 변하지 않게 하는 옵션을 추가하여 해결하였슴당!
[mdn 링크](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/vector-effect)
=> fix: Icon 컴포넌트 smile 이  비율에 따라 stroke-width 가 유지가 안되고 깨지는 현상 수정

packages/react/src/components/Avatar/index.tsx, packages/react/src/components/Image/index.tsx, packages/react/src/components/Radio/Default.tsx, packages/react/src/components/Radio/Input.tsx, packages/react/src/components/Radio/Radio.stories.tsx
- closed #200 
* 상위 요소에 의해 사이즈 틀어지는 이슈 수정
* Radio
* Image
* Avatar
* 외부에서 스타일이 틀어지는 이슈가 있어 wrapping을 통해 사이즈를 조절해야하는 이슈가 있었습니다. 컴포넌트에 직접 width, height를 전달해 사이즈를 지정하는 의미가 있도록 하기 위해 **`min-width`**, **`max-width`** 를 지정하여 컴포넌트가 고정값으로 가질 수 있도록 했습니다.
* 상위에서 사이즈를 자유롭게 조절하기를 원한다면 100%로 지정하여 wrapping을 통해 사이즈를 조절하도록 합니다.
=> design: 상위 요소에 의해 사이즈 틀어지는 이슈 수정

.changeset/eleven-keys-taste.md, packages/react/src/components/Image/index.tsx
- closed #221 
- 1.27 버전 이후 변경 사항을 확인해보니 maxWidth, minWidth, maxHeight, minHeight에 boxSize로 대응이 되어 있어 해당 값을 각각 받도록 수정하였습니다.
=> fix: 이미지 미디어쿼리 대응 이슈 해결

.changeset/three-cobras-agree.md, packages/react/src/components/SelectBox/index.tsx
- closed #240 
* Selectbox 컴포넌트 dark일 때 폰트 색상 white 적용되도록 수정
=> design: Selectbox 컴포넌트 dark일 때 스타일 이슈 수정 

.changeset/shiny-cars-attend.md, packages/react/src/components/Input/Edit.tsx
- closed #261 
* Input.Edit 가격이 아닌 경우도 가능하도록
isPrice 아닌 상황에도 사용되는 곳이 있어 수정합니다.
=> fix: Input.Edit 가격이 아닌 경우도 가능하도록

.changeset/angry-nails-fly.md, packages/react/src/components/Carousel/index.tsx, packages/react/src/components/ImageModal/index.tsx
- closed #258 
* ImageModal 이미지 처음 위치 못잡는 이슈 수정
* Carousel 이미지 클릭 이벤트 받기
=> fix: ImageModal, Carousel 수정
